version: "2"

run:
  timeout: 30m

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - atomicalign
      - fieldalignment
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
      - name: var-naming

linters:
  disable-all: true
  enable:
    - testifylint
    - tparallel
    - bodyclose
    - containedctx
    - govet
    - ineffassign
    - staticcheck
    - unused
    - ginkgolinter
    - gocritic
    - makezero
    - misspell
    - prealloc
    - revive

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gci:
      sections:
        # Standard section: captures all standard packages.
        - standard
        # Default section: contains all imports that could not be matched to another section type.
        - default
        # Custom section: groups all imports with the specified Prefix.
        - prefix(github.com/ubie-oss)
      skip-generated: true
      custom-order: true

