name: Publish Docker image
on:
  push:
    tags:
    - 'v*'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Docker Registry
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
      with:
        images: docker.pkg.github.com/ubie-oss/cron-hpa/cron-hpa-controller
    - name: Build container image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
